- path: /
  domain: jellyfin.lawcky.net
  target: http://localhost:8096
  display_name: "Jellyfin"
  description: "Jellyfin Media Server (Netflix alternative), not always up."
  icon: "/static/icons/jellyfin.png"
  need_auth: true
  is_admin: false
 
- path: /
  domain: affine.lawcky.net
  target: http://localhost:3010
  display_name: "Affine (not yet)"
  description: "Affine Note-taking app"
  icon: "static/icons/affine.png"
  need_auth: false
  is_admin: false

- path: /
  domain: truenas.lawcky.net
  target: http://10.0.0.201
  display_name: "TrueNas"
  description: "TrueNas Portal"
  icon: "static/icons/affine.png"
  need_auth: true
  is_admin: true

- path: /site
  domain: 
  target: http://localhost:8080
  display_name: "My Legacy Website"
  description: "My personal hold website for CTFs (DB is not up)"
  icon: "static/icons/archi.png"
  need_auth: false
  is_admin: false
